-- Assessment Metadata Registry projection schema (amr.registry.v1)
--
-- A SELF-CONTAINED, year-keyed SQLite projection of the authored Tier A sidecars
-- (amr.assessment_system.v1). Unlike the SGPc store DDL (which is additive to a
-- microdata store and borrows its identity dimensions), this schema is standalone:
-- it carries its own identity dimensions so the registry DB stands alone.
--
-- DERIVED, NOT CANONICAL. Generated by tools/build.py from metadata/*.json on every
-- build. Never hand-edit; never treat as a source of truth. Everything is YEAR-KEYED so
-- a performance-level re-establishment (new cutscores / renamed levels in some year) is
-- recorded faithfully and "what was true in 2017?" is a WHERE year = '2017'.

PRAGMA foreign_keys = ON;

-- Build provenance: one row, the commit + schema the DB was generated from.
CREATE TABLE IF NOT EXISTS registry_meta (
  key   TEXT PRIMARY KEY,
  value TEXT
);

-- Identity: invariant per (jurisdiction, assessment_system). Names can drift across
-- years, so descriptive names live in the year-keyed tables; identity is the stable key.
CREATE TABLE IF NOT EXISTS jurisdiction (
  jurisdiction_id TEXT PRIMARY KEY,
  name            TEXT NOT NULL,
  type            TEXT NOT NULL,
  nces_id         TEXT,
  fips            TEXT
);

CREATE TABLE IF NOT EXISTS assessment_system (
  assessment_system_id TEXT PRIMARY KEY,
  name                 TEXT NOT NULL,
  family               TEXT NOT NULL,
  assessment_type      TEXT NOT NULL
);

-- One row per authored sidecar (the year-resolved record) + its governance status.
CREATE TABLE IF NOT EXISTS administration (
  jurisdiction_id      TEXT NOT NULL,
  assessment_system_id TEXT NOT NULL,
  year                 TEXT NOT NULL,
  administration_id    TEXT,
  vendor               TEXT,
  window               TEXT,
  csem_ref             TEXT,
  status               TEXT NOT NULL,
  source_confidence    TEXT,
  source_citation      TEXT,
  PRIMARY KEY (jurisdiction_id, assessment_system_id, year)
);

-- Descriptive program facts, per year (names/orgs can change over time).
CREATE TABLE IF NOT EXISTS assessment_program (
  jurisdiction_id           TEXT NOT NULL,
  assessment_system_id      TEXT NOT NULL,
  year                      TEXT NOT NULL,
  assessment_name           TEXT,
  abbreviation              TEXT,
  organization_name         TEXT,
  organization_abbreviation TEXT,
  organization_url          TEXT,
  PRIMARY KEY (jurisdiction_id, assessment_system_id, year)
);

-- Vertical-scale flag per content area, year-keyed.
CREATE TABLE IF NOT EXISTS vertical_scale (
  jurisdiction_id      TEXT NOT NULL,
  assessment_system_id TEXT NOT NULL,
  content_area         TEXT NOT NULL,
  year                 TEXT NOT NULL,
  vertical_scale       INTEGER NOT NULL,
  scale_name           TEXT,
  label                TEXT,
  PRIMARY KEY (jurisdiction_id, assessment_system_id, content_area, year)
);

-- Achievement-level labels (+ proficiency mapping) per content area, year-keyed.
CREATE TABLE IF NOT EXISTS achievement_level (
  jurisdiction_id      TEXT NOT NULL,
  assessment_system_id TEXT NOT NULL,
  content_area         TEXT NOT NULL,
  year                 TEXT NOT NULL,
  level_index          INTEGER NOT NULL,
  label                TEXT NOT NULL,
  proficient           INTEGER,
  PRIMARY KEY (jurisdiction_id, assessment_system_id, content_area, year, level_index)
);

-- Cutscores: the LOWER BOUND of each performance level, per content area x grade x year.
-- level_index 1 is the lower bound of the second level (the first cut).
CREATE TABLE IF NOT EXISTS cutscore (
  jurisdiction_id      TEXT NOT NULL,
  assessment_system_id TEXT NOT NULL,
  content_area         TEXT NOT NULL,
  year                 TEXT NOT NULL,
  grade                TEXT NOT NULL,
  level_index          INTEGER NOT NULL,
  lower_bound          REAL NOT NULL,
  PRIMARY KEY (jurisdiction_id, assessment_system_id, content_area, year, grade, level_index)
);

-- Year-resolved comparability to the prior administered year (scale breaks,
-- vendor/blueprint changes, administration gaps). One row per assessment record.
CREATE TABLE IF NOT EXISTS comparability (
  jurisdiction_id          TEXT NOT NULL,
  assessment_system_id     TEXT NOT NULL,
  year                     TEXT NOT NULL,
  administered             INTEGER,
  scale_transition         INTEGER,
  comparable_to_prior_year INTEGER,
  prior_scale_name         TEXT,
  notes                    TEXT,
  PRIMARY KEY (jurisdiction_id, assessment_system_id, year)
);

-- Accountability system identity (state-wide; USES assessment systems).
CREATE TABLE IF NOT EXISTS accountability_system (
  accountability_system_id TEXT PRIMARY KEY,
  name                     TEXT NOT NULL,
  framework                TEXT
);

-- Criterion-referenced achievement TARGETS -- state policy, authored in accountability
-- records (NOT the assessment). Each target cross-links the assessment system + content
-- area it applies to. semantics: exit | proficiency; basis: proficiency_boundary (resolve
-- from the linked assessment's cutscores) | scale_score (explicit per-grade thresholds).
CREATE TABLE IF NOT EXISTS accountability_target (
  jurisdiction_id          TEXT NOT NULL,
  accountability_system_id TEXT NOT NULL,
  assessment_system_id     TEXT NOT NULL,
  content_area             TEXT NOT NULL,
  year                     TEXT NOT NULL,
  label                    TEXT,
  semantics                TEXT NOT NULL,
  basis                    TEXT NOT NULL,
  comparison               TEXT,
  status                   TEXT,
  source_confidence        TEXT,
  PRIMARY KEY (jurisdiction_id, accountability_system_id, assessment_system_id, content_area, year)
);

-- Per-grade scale-score thresholds for basis='scale_score' targets (e.g. WIDA exit).
CREATE TABLE IF NOT EXISTS accountability_target_scale_score (
  jurisdiction_id          TEXT NOT NULL,
  accountability_system_id TEXT NOT NULL,
  assessment_system_id     TEXT NOT NULL,
  content_area             TEXT NOT NULL,
  year                     TEXT NOT NULL,
  grade                    TEXT NOT NULL,
  scale_score              REAL NOT NULL,
  PRIMARY KEY (jurisdiction_id, accountability_system_id, assessment_system_id, content_area, year, grade)
);

CREATE INDEX IF NOT EXISTS idx_admin_cell     ON administration (jurisdiction_id, assessment_system_id, year);
CREATE INDEX IF NOT EXISTS idx_vendor_year    ON administration (vendor, year);
CREATE INDEX IF NOT EXISTS idx_vscale_cell    ON vertical_scale (vertical_scale, year);
CREATE INDEX IF NOT EXISTS idx_cutscore_cell  ON cutscore (jurisdiction_id, assessment_system_id, content_area, year, grade);
CREATE INDEX IF NOT EXISTS idx_target_link    ON accountability_target (assessment_system_id, content_area, year);
